P8105_hw2_qc2385
================
Qixuan Cao
2026-10-06

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## problem 1

access the data:

``` r
subway_df = 
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  janitor::clean_names() |>
  select(
    line, station_name, station_latitude, station_longitude,
    route1:route11, entry, vending, entrance_type, ada
  ) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

short paragraph about this dataset:

The cleaned NYC subway dataset contains 1868 observations and 19
variables.

The dataset includes subway line and station name, station latitude and
longitude, routes served, entry status, vending availability, entrance
type, and ADA compliance.

These data are not completely tidy because the subway routes are stored
across multiple columns (`route1` through `route11`) rather than in a
single route variable.

### problem 1a

How many distinct stations are there?

``` r
subway_df |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

There are 465 distinct subway stations.

### problem 1b

How many stations are ADA compliant?

``` r
subway_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

There are 84 ADA-compliant stations.

### problem 1c

What proportion of station entrances / exits without vending allow
entrance?

``` r
subway_df |>
  filter(vending == "NO") |>
  summarize(
    proportion_entry = mean(entry, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   proportion_entry
    ##              <dbl>
    ## 1            0.377

Among station entrances and exits without vending, the proportion that
allow entrance is 37.7%.

## problem 1 reformat data

``` r
subway_tidy =
  subway_df |>
  mutate(across(route8:route11, as.character)) |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name"
  ) |>
  filter(!is.na(route_name))
```

### problem 1 reformat a

How many distinct stations are there?

``` r
subway_tidy |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 60

There are 60 distinct subway stations.

### problem 1 reformat b

How many stations are ADA compliant?

``` r
subway_tidy |>
  filter(route_name == "A", ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 17

There are 17 ADA-compliant stations.

## Problem 2

``` r
library(readxl)
```

``` r
mr_trash =
 read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N709"
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    year = as.numeric(year),
    trash_wheel = "Mr. Trash Wheel"
  )
```

``` r
professor_trash =
   read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M134"
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year = as.numeric(year),
    trash_wheel = "Professor Trash Wheel"
  )
```

``` r
gwynnda_trash =
  read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynns Falls Trash Wheel",
    range = "A2:L351"
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year = as.numeric(year),
    trash_wheel = "Gwynnda"
  )
```

``` r
trash_wheel_df =
  bind_rows(
    mr_trash,
    professor_trash,
    gwynnda_trash
  )
```

What was the total weight of trash collected by Professor Trash Wheel?

``` r
trash_wheel_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarize(
    total_weight = sum(weight_tons, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         282.

The total weight of trash collected by Professor Trash Wheel was 282
tons.

What was the total number of cigarette butts collected by Gwynnda in
June of 2022?

``` r
trash_wheel_df |>
  filter(
    trash_wheel == "Gwynnda",
    year == 2022,
    month == "June"
  ) |>
  summarize(
    total_cigarette_butts = sum(cigarette_butts, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   total_cigarette_butts
    ##                   <dbl>
    ## 1                 18120

Gwynnda collected 18120 cigarette butts in June 2022.

## Problem 3

``` r
baseline_df =
  read_csv("data/MCI_baseline.csv", skip = 1, na = ".") |>
  janitor::clean_names() |>
  mutate(
    sex = if_else(sex == 1, "male", "female"),
    apoe4 = if_else(apoe4 == 1, "carrier", "non-carrier")
  ) |>
  filter(is.na(age_at_onset) | age_at_onset > current_age)
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
baseline_df |>
  summarize(
    participants = n(),
    developed_mci = sum(!is.na(age_at_onset)),
    mean_baseline_age = mean(current_age)
  )
```

    ## # A tibble: 1 × 3
    ##   participants developed_mci mean_baseline_age
    ##          <int>         <int>             <dbl>
    ## 1          479            93              65.0

``` r
baseline_df |>
  filter(sex == "female") |>
  summarize(
    apoe4_proportion = mean(apoe4 == "carrier")
  )
```

    ## # A tibble: 1 × 1
    ##   apoe4_proportion
    ##              <dbl>
    ## 1              0.3

### problem 3 basline:

The baseline dataset was imported with `skip = 1` to remove the
descriptive first row, and `"."` was treated as missing. Sex and APOE4
status were recoded from 0/1 into labeled categories. The dataset
includes participant ID, baseline age, sex, years of education, APOE4
carrier status, and age at MCI onset, which is missing for participants
who remained MCI-free during follow-up. Participants whose age at onset
was at or before their baseline age were excluded, as they did not meet
the inclusion criterion. A total of 483 participants were recruited.
After excluding 4 who already had MCI at baseline, 479 remained, of whom
93 developed MCI during follow-up. The average baseline age was 65.0
years. Among women in the study, 30.0% were APOE4 carriers.

``` r
amyloid_df =
  read_csv("data/mci_amyloid.csv", skip = 1, na = c("NA", "Na")) |>
  janitor::clean_names() |>
  rename(id = study_id) |>
  pivot_longer(
    baseline:time_8,
    names_to = "time",
    values_to = "amyloid_ratio"
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Problem 3 amyloid:

The amyloid dataset was imported with `skip = 1` to remove the
descriptive first row. Missing values were recorded as both `"NA"` and
`"Na"`, so both were treated as missing during import. The ID variable
was renamed from `study_id` to `id` to match the baseline dataset.
Because the original dataset was in wide format, with separate columns
for measurements at baseline and times 2, 4, 6, and 8, `pivot_longer()`
was used to reshape the data into a tidy long format with one row per
participant per visit. The dataset contains amyloid β 42/40 ratio
measurements for 487 participants.

``` r
mci_df =
  inner_join(baseline_df, amyloid_df, by = "id")

mci_df |>
  summarize(
    participants = n_distinct(id),
    rows = n(),
    columns = ncol(mci_df)
  )
```

    ## # A tibble: 1 × 3
    ##   participants  rows columns
    ##          <int> <int>   <int>
    ## 1          471  2355       8

``` r
baseline_df |>
  anti_join(amyloid_df, by = "id") |>
  pull(id)
```

    ## [1]  14  49  92 179 268 304 389 412

``` r
amyloid_df |>
  distinct(id) |>
  anti_join(baseline_df, by = "id") |>
  pull(id)
```

    ##  [1]  72 234 283 380 484 485 486 487 488 489 490 491 492 493 494 495

``` r
write_csv(mci_df, "data/mci_combined.csv")
```

### problem 3 combined:

Eight participants appeared only in the baseline dataset and therefore
had no biomarker measurements. Sixteen participants appeared only in the
amyloid dataset. Four of these participants (IDs 72, 234, 283, and 380)
were present in the original baseline dataset but were excluded because
they had MCI at baseline, while the remaining twelve participants (IDs
484–495) were not present in the baseline dataset. After retaining only
participants who appeared in both datasets, the combined dataset
contained 471 participants and 2355 observations. The final dataset
included 8 variables describing participant demographics, visit time,
and amyloid β 42/40 ratio. The combined dataset was exported as
`mci_combined.csv` to the data directory.
